name: Publish to NPM
on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
  workflow_dispatch:
jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          standalone: true
          run_install: false

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint:check

      - name: Build
        run: pnpm exec tsc

      - name: SetupAuth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package on NPM 📦
        run: pnpm publish -r
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
